language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

sudo: false

env:
  - TEST_SECURE=6001
  - TEST_PLAIN=6000

install:
  - composer install --prefer-source --no-interaction
  - sudo apt-get install -y openssl stunnel
  - openssl genrsa 1024 > stunnel.key
  - openssl req -batch -subj '/CN=127.0.0.1' -new -x509 -nodes -sha1 -days 3650 -key stunnel.key > stunnel.cert
  - cat stunnel.cert stunnel.key > stunnel.pem
  - stunnel -f -p stunnel.pem -d $TEST_SECURE -r $TEST_PLAIN 2>/dev/null &

script:
  - phpunit --coverage-text
